### ISSUE TITLE
Remove scripts/ folder from repo

### ISSUE THREAD

**Issue by oscard0m** [octoherd/octoherd#7]
Since the migration was done already and README.md is talking about it, would have sense to remove the entire `scripts` folder from the repo?

Other changes:
- Replace `scripts` for `octoherd` in
   - `package.json`
   - `settings.yml`

**Comment by gr2m** [comment]
I'd like to leave the scripts folders because links to them have been shared and the redirect still works:
https://github.com/octoherd/scripts/tree/main/scripts/close-renovate-dashboard-issues#readme

We can remove at end of April.



> Replace `scripts` for `octoherd` in
> 
>     * `package.json`
> 
>     * `settings.yml`

we can remove the `package*.json` files altogether.

And I totally forgot I've setup the settings app :) Yes, we should update the name and description in there
